version: '{build}'

environment:
  APPVEYOR: 1
  DEPLOY: 0
  MYSQL_VERSION: mysql-5.7.14-win32
  APNG_PLUGIN: apng-1.1.05.10.1

  matrix:
    # MSVC x86
    - PLATFORM: amd64_x86
      QTDIR: C:\Qt\5.10.1\msvc2015
      MAKE: nmake
      MAKEFILES: NMake Makefiles
      DEPLOY: 1

    # MSVC x64
    - PLATFORM: amd64
      QTDIR: C:\Qt\5.10.1\msvc2015_64
      MAKE: nmake
      MAKEFILES: NMake Makefiles

    # MinGW
    - PLATFORM: mingw
      QTDIR: C:\Qt\5.10.1\mingw53_32
      MAKE: mingw32-make
      MAKEFILES: MinGW Makefiles

cache:
  - release\sites\node_modules -> release\sites\package.json
  - mysql-5.7.14-win32 -> .appveyor.yml
  - apng-1.1.05.10.1 -> .appveyor.yml

init:
  - git config --global core.autocrlf input
  - if %PLATFORM%==mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %PLATFORM%==mingw set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%
  - set PATH=%QTDIR%\bin;%PATH%
  - if not %PLATFORM%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "%MAKEFILES%" -DCMAKE_BUILD_TYPE=Release
  - if not %PLATFORM%==mingw (nmake) else (mingw32-make)
  - cd ..
  - if %APPVEYOR_REPO_TAG%==true (set GRABBER_VERSION="%APPVEYOR_REPO_TAG_NAME%") else (set GRABBER_VERSION="nightly")
  - if %DEPLOY%==1 if not exist %APNG_PLUGIN% curl -L https://install.skycoder42.de/qtmodules/windows_x86/qt5101/qt.qt5.5101.skycoder42.png.win32_msvc2015/1.1.05.10.1.7z -o "%APNG_PLUGIN%.7z"
  - if %DEPLOY%==1 if not exist %APNG_PLUGIN% 7z x "%APNG_PLUGIN%.7z" -y -o"%APNG_PLUGIN%"
  - if %DEPLOY%==1 if not exist %MYSQL_VERSION% curl -L -O "https://dev.mysql.com/get/Downloads/MySQL-5.7/%MYSQL_VERSION%.zip"
  - if %DEPLOY%==1 if not exist %MYSQL_VERSION% 7z x "%MYSQL_VERSION%.zip" -y
  - if %DEPLOY%==1 iscc /Q /DMyAppVersion="%GRABBER_VERSION%" /DQtDir="%QTDIR%\bin" /DOpenSSLDir="C:\OpenSSL-Win32" /DMySQLDir="%APPVEYOR_BUILD_FOLDER%\%MYSQL_VERSION%" /DQtApngDll="%APPVEYOR_BUILD_FOLDER%\%APNG_PLUGIN%\5.10.1\msvc2015\plugins\imageformats\qapng.dll" releases/setup.iss

test_script:
  - build\tests\tests.exe

artifacts:
  - path: releases\Grabber_*.exe
    name: windows_setup

deploy:
  # Nightly
  - provider: GitHub
    tag: nightly
    release: Nightly
    draft: false
    prerelease: true
    force_update: true
    artifact: windows_setup
    description: |
      Nightly automated builds from the develop branch.
      Automatically uploaded by AppVeyor, **use at your own risk**!

      **Head:** $(APPVEYOR_REPO_COMMIT)
      **Date:** $(APPVEYOR_REPO_COMMIT_TIMESTAMP)
    auth_token:
      secure: mUYQ72KBJUaYr5Bhy2HkBkEY13Q7k27Q7IRmOGXfTOq7YnXUS9PikETcZvzCfiVu
    on:
      branch: develop
      DEPLOY: 1

  # Releases
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    draft: true
    prerelease: false
    force_update: true
    artifact: windows_setup
    auth_token:
      secure: mUYQ72KBJUaYr5Bhy2HkBkEY13Q7k27Q7IRmOGXfTOq7YnXUS9PikETcZvzCfiVu
    on:
      APPVEYOR_REPO_TAG: true
      DEPLOY: 1
