name: MacOS
on: [push]

jobs:
  MacOS:
    timeout-minutes: 15
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set environment
      run: |
        echo ::set-env name=GRABBER_VERSION::nightly
        echo ::set-env name=GRABBER_IS_NIGHTLY::1
        echo ::set-env name=PLATFORM_NAME::x64
        echo ::set-env name=OPENSSL_ROOT_DIR::/usr/local/opt/openssl/

    - name: Install packages
      run: pip3 install opencv-python opencv-python-headless

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.7.2
      with:
        version: 5.12.6

    - name: Create build dir
      run: mkdir build

    - name: Configure
      working-directory: build
      run: cmake ../src -DCMAKE_BUILD_TYPE=Release -DNIGHTLY=%GRABBER_IS_NIGHTLY% -DCOMMIT="%GITHUB_SHA%" -DVERSION="%GRABBER_VERSION%"

    - name: Compile
      working-directory: build
      run: |
        cmake --build . --config Release --target sites
        cmake --build . --config Release

    - name: Test
      working-directory: src
      run: ../build/tests/tests

    - name: Generate package
      run: ./scripts/package-mac.sh
