name: Uncrustify
on: [push, pull_request]

jobs:
  Linux:
    timeout-minutes: 10
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Uncrustify cache
      uses: actions/cache@v1
      id: bin-cache
      with:
        path: bin
        key: ${{ runner.os }}-bin-${{ hashFiles('.github/workflows/uncrustify.yml') }}

    - name: Build uncrustify
      if: steps.bin-cache.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/uncrustify/uncrustify.git uncrustify_git
        cd uncrustify_git
        git checkout 8edb7262e855c4271e9e5fc26af93861103e14fa
        cd ..
        mkdir uncrustify_build
        cd uncrustify_build
        cmake ../uncrustify_git
        cmake --build .
        mkdir $GITHUB_WORKSPACE/bin
        cp uncrustify $GITHUB_WORKSPACE/bin
        cd ..

    - name: Add bin to path
      run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Print uncrustify version
      run: uncrustify -v

    - name: Run uncrustify
      run: ./scripts/uncrustify.sh

    - name: Check diff
      run: git diff --exit-code
